title: Knoppen gebruiken om een actie te activeren
hero_image: images/banner.png
description: Gebruik de fysieke micro:bit-knoppen om een actie te activeren
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Inleiding
