title: Utiliser des boutons pour déclencher une action
hero_image: images/banner.png
description: Utilise les boutons physiques du micro:bit pour déclencher une action
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Introduction
